site_name: MelodiApp - Documentación
site_description: Documentación y bitácora del proyecto
site_url: https://melodiapp.github.io/documentation/
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
nav:
  - Inicio: index.md
  - Arquitectura:
    - Visión General: arquitectura/arquitectura.md
    - Backend: arquitectura/backend.md
    - Frontend Móvil: arquitectura/frontend_movil.md
    - Frontend Web: arquitectura/frontend_web.md
    - Diagramas: arquitectura/diagramas.md
  - General:
    - Introducción: general/general.md
    - Decisiones: general/decisiones.md
    - Dificultades: general/dificultades.md
    - Checkpoints: general/checkpoints.md
  - APIs:
    - Especificaciones: apis.md
  - Contribuir:
    - Cómo colaborar: contribuir.md